###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-mayikt-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
#####Swagger相关配置(后期放置在阿波罗)
#访问地址http://localhost:8300/swagger-ui.html
swagger:
  base-package: com.mayikt.member.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目基于SpringCloud2.x构建微服务电商项目，
  version: 1.0
#  terms-of-service-url: www.mayikt.com
  contact:
    name: gehui
    email: gehui121@163.com

