###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-mayikt-zuul
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
##配置网关反向代理，即路由分发(需要写在阿波罗配置文件中)
zuul:
  routes:
    api-a:
      path: /api-member/**
      serviceId: app-mayikt-member
    api-b:
      path: /api-weixin/**
      serviceId: app-mayikt-weixin
