server:
  port: 30002
spring:
  application:
    name: eureka-hello-customer
eureka:
  instance:
  ##使用ip注册
    prefer-ip-address: true
    ##自定义实例编号
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    ##客户端向注册中心发送心跳检测时间间隔
    lease-renewal-interval-in-seconds: 30
    ##客户端失效时间
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      ##注册地址api为eureka-server账号，node为密码
      defaultZone: http://api:node@server1:10001/eureka/,http://api:node@server2:10002/eureka/