server:
  port: 10002
##服务名称
spring:
  application:
    name: eureka-server
  security:
    user:
      name: api
      password: node
      roles: SERVICE_NODE
eureka:
  instance:
    ##服务实例名称
    hostname: server2
    prefer-ip-address: true
    ##注册服务实例
    instance-id: ${eureka.instance.hostname}:${server.port}@project.version@
  client:
    service-url:
      ##注册中心地址
      defaultZone: http://server1:10001/eureka/
  server:
    ##集群节点之间读取超时时间，单位：毫秒
      peer-node-read-timeout-ms: 1000

    ##是否将自己作为服务注册到注册中心
    #register-with-eureka: false
    ##是否校验服务存在
    #fetch-registry: false
