server:
  port: 20001
spring:
  application:
    name: hello-service
eureka:
  instance:
    prefer-ip-address: true
    ##自定义实例编号
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    ##心跳检测与续约时间，开发环境将时间设置小些，保证服务不可用及时将服务剔除掉
    ##客户端向注册中子心发送心跳的时间间隔，单位：秒
    lease-renewal-interval-in-seconds: 1
    ##服务端在收到最后一次心跳之后等待的时间，也就是客户端失效时间，单位：秒
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
    #添加注册服务时安全信息认证api是Eureka Server中配置的用户名，node是密码，@后面的是是Eureka Server地址
      defaultZone: http://api:node@server1:10001/eureka/,http://api:node@server2:10002/eureka/
